add_rules("mode.debug", "mode.release")
set_toolchains("clang")
set_languages("cxxlatest")
add_requires("raylib", "flecs")
target("yaldabaranth")
set_kind("binary")
set_rundir(os.projectdir())
add_files("src/*.cpp")
add_packages("raylib", "flecs")
